- hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml
