- name: Copy .gitconfig
  become_user: "{{ lookup('env', 'USER') }}"
  copy:
    src: "./.gitconfig"
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

# - name: Ensure .ssh directory exists
#   become_user: "{{ lookup('env', 'USER') }}"
#   file:
#     dest: "{{ dest_key | dirname }}"
#     mode: 0700
#     state: directory
#   tags:
#     - dotfiles
#     - install
#     - ssh

- name: Copy keys
  become_user: "{{ lookup('env', 'USER') }}"
  copy:
    src: "./.ssh"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

# - name: Install ssh key
#   become_user: "{{ lookup('env', 'USER') }}"
#   copy:
#     src: "{{ source_key }}"
#     dest: "{{ dest_key }}"
#     mode: 0600
#   tags:
#     - dotfiles
#     - install
#     - ssh

- name: Set authorized key
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "./.ssh/"
  tags:
    - dotfiles
    - install
    - ssh
