- name: Copy keys
  become_user: "{{ user }}"
  copy:
    src: "./.ssh"
    dest: "{{ home }}"
    owner: "{{ user }}:{{ user }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

# https://docs.ansible.com/ansible/2.5/modules/authorized_key_module.html#examples
- name: Set authorized key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', home + '/.ssh/id_ed25519.pub') }}"
  tags:
    - dotfiles
    - install
    - ssh
